services:
  - type: web
    name: urban-sound-narrative
    env: docker  # Switch to Docker
    dockerfilePath: ./Dockerfile  # Point to it
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
    autoDeploy: true