services:
  - type: web
    name: urban-audio-api
    runtime: docker
    plan: free
    region: oregon
    rootDir: backend
    dockerfilePath: ./Dockerfile
    dockerContext: ./backend
    dockerCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: PORT
        value: 10000