services:
  - type: web
    name: urban-audio-api
    runtime: docker
    plan: free
    region: oregon
    rootDir: backend
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    envVars:
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false